### ISSUE TITLE
Broken build on 32-bit with 7.4

### ISSUE THREAD

**Issue by remicollet** [SeasX/SeasLog#286]
```
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~

```

**Comment by remicollet** [comment]
See comment on  https://github.com/SeasX/SeasLog/commit/941a0c67cbafe157d39ee8e5988aced3e92df117#diff-9813ab0309486138e6f02d7dd02dc3ef

**Comment by 769344359** [comment]
what's your php version ?

**Comment by 769344359** [comment]
@remicollet

**Comment by remicollet** [comment]
Issue is with 7.4

Proposal: simply use `zend_ulong` everywhere, it exists since PHP 4.3

**Comment by 769344359** [comment]
https://github.com/php/php-src/commit/bebcdcc74573b015c22238dbc9b2698c88b7a601# 
the ulong  is removed by this push request

**Comment by 769344359** [comment]
it may conflicting with other  type 

-  can you give the **full error message**  near by `error: conflicting types for 'ulong'`?


```
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
```
@remicollet

**Comment by remicollet** [comment]
```
In file included from ./include/SeasLog.h:30,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Appender.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Appender.c:17:
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Appender.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Appender.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Appender.c: In function 'appender_handle_tcp_udp':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Appender.c:105:18: warning: variable 'log_context_len' set but not used [-Wunused-but-set-variable]
     int log_len, log_context_len, PRI;
                  ^~~~~~~~~~~~~~~
In file included from ./include/SeasLog.h:30,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Performance.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Performance.c:17:
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Performance.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Performance.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Performance.c: In function 'performance_frame_end':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Performance.c:427:20: warning: unused variable 'previous_frame' [-Wunused-variable]
     seaslog_frame *previous_frame = current_frame->previous_frame;
                    ^~~~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Performance.c: In function 'process_seaslog_performance_log':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Performance.c:551:11: warning: unused variable 'j' [-Wunused-variable]
     int i,j,m,n,r,stack_level = 0;
           ^
make: *** [Makefile:203: src/Appender.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:193: src/Performance.lo] Error 1
In file included from ./include/SeasLog.h:30,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/ExceptionHook.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/ExceptionHook.c:17:
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/ExceptionHook.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/ExceptionHook.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
make: *** [Makefile:201: src/ExceptionHook.lo] Error 1
In file included from ./include/SeasLog.h:30,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Logger.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Logger.c:17:
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Logger.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Logger.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Logger.c: In function 'seaslog_init_logger_list':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Logger.c:159:11: warning: unused variable 'z_logger_list' [-Wunused-variable]
     zval *z_logger_list;
           ^~~~~~~~~~~~~
make: *** [Makefile:207: src/Logger.lo] Error 1
In file included from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/SeasLog.h:30,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:17:
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/SeasLog.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c: In function 'seaslog_log_by_level_common_ex':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:401:18: warning: variable 'str_key' set but not used [-Wunused-but-set-variable]
     zend_string *str_key;
                  ^~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:400:16: warning: variable 'num_key' set but not used [-Wunused-but-set-variable]
     zend_ulong num_key;
                ^~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:397:12: warning: unused variable 'ppzval' [-Wunused-variable]
     zval **ppzval;
            ^~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c: In function 'zim_SEASLOG_RES_NAME_setRequestID':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:755:84: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'zend_long' {aka 'int'} [-Wformat=]
                 SEASLOG_G(request_id_len) = spprintf(&SEASLOG_G(request_id), 0, "%ld", Z_LVAL_P(_request_id));
                                                                                  ~~^
                                                                                  %d
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c: In function 'zim_SEASLOG_RES_NAME_analyzerCount':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:881:42: warning: unused variable 'key_word_len' [-Wunused-variable]
     int log_path_len = 0, level_len = 0, key_word_len = 0;
                                          ^~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:881:27: warning: unused variable 'level_len' [-Wunused-variable]
     int log_path_len = 0, level_len = 0, key_word_len = 0;
                           ^~~~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:881:9: warning: unused variable 'log_path_len' [-Wunused-variable]
     int log_path_len = 0, level_len = 0, key_word_len = 0;
         ^~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:880:9: warning: unused variable 'len' [-Wunused-variable]
     int len = 0;
         ^~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c: In function 'zim_SEASLOG_RES_NAME_analyzerDetail':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:971:42: warning: unused variable 'key_word_len' [-Wunused-variable]
     int log_path_len = 0, level_len = 0, key_word_len = 0;
                                          ^~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:971:27: warning: unused variable 'level_len' [-Wunused-variable]
     int log_path_len = 0, level_len = 0, key_word_len = 0;
                           ^~~~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:971:9: warning: unused variable 'log_path_len' [-Wunused-variable]
     int log_path_len = 0, level_len = 0, key_word_len = 0;
         ^~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c: In function 'zim_SEASLOG_RES_NAME_log':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:1135:12: warning: unused variable 'ppzval' [-Wunused-variable]
     zval **ppzval;
            ^~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:1134:11: warning: unused variable 'pzval' [-Wunused-variable]
     zval *pzval;
           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/seaslog.c:1133:16: warning: unused variable 'msght' [-Wunused-variable]
     HashTable *msght;
                ^~~~~
make: *** [Makefile:191: seaslog.lo] Error 1
In file included from ./include/SeasLog.h:30,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Analyzer.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Analyzer.c:17:
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Analyzer.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Analyzer.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Analyzer.c: In function 'get_type_count':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Analyzer.c:119:15: warning: unused variable 'temp_p' [-Wunused-variable]
         char *temp_p = fgets(buffer, sizeof(buffer), fp);
               ^~~~~~
make: *** [Makefile:195: src/Analyzer.lo] Error 1
In file included from ./include/SeasLog.h:30,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Buffer.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Buffer.c:17:
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Buffer.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Buffer.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Buffer.c: In function 'seaslog_init_buffer':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Buffer.c:46:11: warning: unused variable 'z_buffer' [-Wunused-variable]
     zval *z_buffer;
           ^~~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Buffer.c: In function 'real_php_log_buffer':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Buffer.c:75:18: warning: variable 'str_key' set but not used [-Wunused-but-set-variable]
     zend_string *str_key;
                  ^~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Buffer.c:74:16: warning: variable 'num_key' set but not used [-Wunused-but-set-variable]
     zend_ulong num_key;
                ^~~~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Buffer.c: In function 'seaslog_shutdown_buffer':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Buffer.c:199:16: warning: variable 'num_key' set but not used [-Wunused-but-set-variable]
     zend_ulong num_key;
                ^~~~~~~
make: *** [Makefile:209: src/Buffer.lo] Error 1
In file included from ./include/SeasLog.h:30,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/TemplateFormatter.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/TemplateFormatter.c:17:
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/TemplateFormatter.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/TemplateFormatter.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/TemplateFormatter.c: In function 'seaslog_template_formatter':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/TemplateFormatter.c:393:1: warning: label 'skip_output' defined but not used [-Wunused-label]
 skip_output:
 ^~~~~~~~~~~
make: *** [Makefile:199: src/TemplateFormatter.lo] Error 1
In file included from ./include/SeasLog.h:30,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/StreamWrapper.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/StreamWrapper.c:17:
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/StreamWrapper.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/StreamWrapper.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/StreamWrapper.c: In function 'seaslog_init_stream_list':
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/StreamWrapper.c:90:11: warning: unused variable 'z_stream_list' [-Wunused-variable]
     zval *z_stream_list;
           ^~~~~~~~~~~~~
make: *** [Makefile:197: src/StreamWrapper.lo] Error 1
In file included from ./include/SeasLog.h:30,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Datetime.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Datetime.c:17:
./include/php7_wrapper.h:23:20: error: conflicting types for 'ulong'
 typedef zend_ulong ulong;
                    ^~~~~
In file included from /usr/include/stdlib.h:394,
                 from /usr/include/php/main/../main/php_config.h:2321,
                 from /usr/include/php/Zend/zend_config.h:1,
                 from /usr/include/php/Zend/zend_portability.h:43,
                 from /usr/include/php/Zend/zend_types.h:25,
                 from /usr/include/php/Zend/zend.h:27,
                 from /usr/include/php/main/php.h:33,
                 from ./include/SeasLog.h:20,
                 from ./php_seaslog.h:24,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/include/Datetime.h:20,
                 from /builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Datetime.c:17:
/usr/include/sys/types.h:148:27: note: previous declaration of 'ulong' was here
 typedef unsigned long int ulong;
                           ^~~~~
/builddir/build/BUILD/php-pecl-seaslog-2.1.0/NTS/src/Datetime.c:138:23: warning: 'seaslog_get_remote_timeout' defined but not used [-Wunused-function]
 static struct timeval seaslog_get_remote_timeout(TSRMLS_D)
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:205: src/Datetime.lo] Error 1


```

**Comment by 769344359** [comment]
What's your gcc version and   glibc version ? 
The error  is  conflicting  from ulong .
it seems different behave between different gcc version,
i try to fix it  ,but i have to Repetition the error.

**Comment by 769344359** [comment]
What's your gcc version and   glibc version ? 
The error  is  conflicting  from ulong .
it seems different behave between different gcc version,
i try to fix it  ,but i have to Repetition the error.
@remicollet

**Comment by remicollet** [comment]
GCC 8.3 (Fedora 29) or 9.2 (Fedora 30)

**Comment by 769344359** [comment]
https://github.com/SeasX/SeasLog/pull/287
